unsigned MAX_PRIMITIVES_IN_LEAF = 10000;

bool OCTANT_TEST_ENABLED = false;
bool PLANE_MASKING_ENABLED = false;
bool PLANE_COHERENCY_ENABLED = false;
bool CAMERA_COHERENCY_ENABLED = false;

unsigned FC_TREE_DEPTH = 0;
unsigned FC_NODE_COUNT = 0;
unsigned FC_NODE_VISITED_COUNT = 0;
float FC_TRAVERSE_TIME = 0;
